### PR TITLE
Merging test code with git history

### PR DESCRIPTION
**Pull request by darstahl**
This merges the testing code repo with history into this repo. It appears to lose file history unfortunately, but preserves the commits.

### CODE REVIEW

**Comment by swernli** [comment]
Nitpick: can you rename the tests folder to "Microsoft.Windows.ComputeVirtualization.Test" so that it matches the sources folder and the actual produced test binary?

**Comment by darstahl** [comment]
Good catch. Updated.

Should we have appveyor at least build the test code? (It don't be able to run without containers for now, but it could build it)

**Comment by swernli** [comment]
Yeah, but I can add that in the next check in.  I'm also going to add vscode tasks for build and test.

**Comment by swernli** [comment]
More nitpicky: I updated my comment (which might not have gone through in email), but the folder shouldn't be plural: Microsoft.Windows.ComputeVirtualization.Test.  As opposed to ".Tests" like it is now.

**Comment by darstahl** [comment]
Changed the namespace to match the folder name instead RE offline discussion.

**Comment by swernli** [comment]
LGTM!

**Pull request merged**
