### PR TITLE
Update to 2.0 SDK

### PR DESCRIPTION
**Pull request by darstahl**
Updating dotnet installer to use the ps1 install script and updating the SDK to 2.0.

This fixes CI issues found in #24 

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by darstahl** [comment]
@jterry75 @swernli PTAL this fixes CI

**Comment by jterry75** [comment]
Nice @darrenstahlmsft - Only feedback I have is that I led you astray. You will want to still call `dotnet build` because the `dotnet pack` that you are calling only validates the build of the actual dll. It doesn't compile any of the samples or tests so a change here could break the build.

**Comment by darstahl** [comment]
Added samples to the SLN file and added back the `dotnet build` step to compile them in CI.

**Comment by darrenstahlmsft** [comment]
There's a build warning due to not referencing a needed package, but I have a followup to fix that

**Comment by darstahl** [comment]
Also pushed a fix to the build warning by adding a reference to `Microsoft.Extensions.DependencyModel` 1.1.0

**Comment by jterry75** [comment]
LGTM

**Pull request merged**
