### PR TITLE
Adds dotnet cli build capabilities.

### PR DESCRIPTION
**Pull request by jterry75**
1. Implements the dotnet cli build capabilities.
2. Adds the xproj resource for Visual Studio builds.

### CODE REVIEW

**Comment by jterry75** [comment]
@darrenstahlmsft - Take a look at this and let me know if this works for you
@swernli - Are you ok with leaving the *.csproj? Or do you think its fine that they can build from *.xproj?

**Comment by darstahl** [comment]
Is this your first publish? Update the version so it doesnt match the nuget published version.

**Comment by swernli** [comment]
Seems good to me.
@jterry75 I'm fine leaving the .csproj as long as they both a) don't get in the way of dotnet build and b) still work.  The only concern would be keeping them up to date if new files are added, which no one just using dotnet to build is going to do.  If that's a concern, or if a or b above aren't true, we should just remove them.

**Comment by jterry75** [comment]
@darrenstahlmsft - This update is now published.
@swernli - Can we follow up and see if I can just remove them. As long as someone has VS2015 Update 2 they can build with *.xproj exactly the same way.

**Comment by jterry75** [comment]
@jstarks - Should we add a nuget nuspec with the *-alpha4 version so that people can use this on .NETCore or not yet?

**Comment by jstarks** [comment]
@jterry75 Let's get the networking PR in before we release alpha4.

**Comment by jterry75** [comment]
I think this resolves all the cli work. But we need to wait for #1 before merge.

**Pull request merged**
